# Warning: This file is generated automatically, and should not be modified.
# Instead, please modify the template in the pr-checks directory and run:
#     pip install ruamel.yaml && python3 sync.py
# to regenerate this file.

name: PR Check - Debug artifact upload
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GO111MODULE: auto
on:
  push:
    branches:
    - main
    - releases/v1
    - releases/v2
    - criemen/debug-action
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - ready_for_review
  workflow_dispatch: {}
jobs:
  debug-artifacts:
    strategy:
      matrix:
        include:
        - os: macos-latest
          version: cached
    name: Debug artifact upload
    timeout-minutes: 45
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Prepare test
      id: prepare-test
      uses: ./.github/prepare-test
      with:
        version: ${{ matrix.version }}
    - uses: ./../action/init
      with:
        tools: ${{ steps.prepare-test.outputs.tools-url }}
        languages: csharp, go
    - name: Build code
      shell: bash
      run: ./build.sh
      env:
        SEMMLE_DEBUG_TRACER: 10000
    - uses: ./../action/analyze
      id: analysis
      timeout-minutes: 1
      env:
        SEMMLE_DEBUG_TRACER: 10000
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: debug-artifact-log
        path: |
          /Users/runner/work/_temp/codeql_databases/
          !/Users/runner/work/_temp/codeql_databases/working/copy-root
