name: PR Check - Swift analysis using autobuild
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GO111MODULE: auto
  CODEQL_EXTRACTOR_JAVA_AGENT_DISABLE_KOTLIN: 'true'
on:
  push:
    branches:
    - adityasharad/swift/autobuild-test
  workflow_dispatch: {}
jobs:
  swift-autobuild:
    strategy:
      matrix:
        include:
        - os: macos-latest
          version: cached
    name: Swift analysis using autobuild
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Prepare test
      id: prepare-test
      uses: ./.github/prepare-test
      with:
        version: ${{ matrix.version }}
    - uses: ./../action/init
      id: init
      with:
        debug: true
        languages: swift
        tools: ${{ steps.prepare-test.outputs.tools-url }}
    - uses: ./../action/.github/setup-swift
      with:
        codeql-path: ${{steps.init.outputs.codeql-path}}
    - name: Check working directory
      shell: bash
      run: pwd
    - uses: ./../action/autobuild
      timeout-minutes: 10
    - uses: ./../action/analyze
      id: analysis
      with:
        upload-database: false
    - name: Check database
      shell: bash
      run: |
        SWIFT_DB="${{ fromJson(steps.analysis.outputs.db-locations).swift }}"
        if [[ ! -d "$SWIFT_DB" ]]; then
          echo "Did not create a database for Swift."
        fi
    - name: Upload artifact
      if: failure() || cancelled()
      uses: actions/upload-artifact@v3
      with:
        name: swift-autobuild-db
        path: ${{ fromJson(steps.analysis.outputs.db-locations).swift }}
    env:
      CODEQL_ENABLE_EXPERIMENTAL_FEATURES_SWIFT: 'true' # Remove when Swift is GA.
      CODEQL_ACTION_TEST_MODE: true
