name: PR Checks (Basic Checks and Runner)

on:
  push:
    branches: [main, releases/v1, releases/v2, criemen/debug-check]
  pull_request:
    # Run checks on reopened draft PRs to support triggering PR checks on draft PRs that were opened
    # by other workflows.
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  runner-analyze-csharp-autobuild-ubuntu:
    name: Runner ubuntu autobuild C# analyze
    timeout-minutes: 45
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Move codeql-action
        shell: bash
        run: |
          mkdir ../action
          mv * .github ../action/
          mv ../action/tests/multi-language-repo/{*,.github} .
          mv ../action/.github/workflows .github
      - name: Build runner
        run: |
          cd ../action/runner
          npm install
          npm run build-runner
      - name: Run init
        run: |
          ../action/runner/dist/codeql-runner-linux init --repository $GITHUB_REPOSITORY --languages csharp --github-url $GITHUB_SERVER_URL --github-auth ${{ github.token }}
      - name: Build code
        run: |
          ../action/runner/dist/codeql-runner-linux autobuild
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: debug-artifact-log
          path: |
            /Users/runner/work/codeql-action/codeql-action/codeql-runner/codeql_databases/
            !/Users/runner/work/codeql-action/codeql-action/codeql-runner/codeql_databases//working/copy-root

      - name: Run analyze
        run: |
          ../action/runner/dist/codeql-runner-linux analyze --repository $GITHUB_REPOSITORY --commit $GITHUB_SHA --ref $GITHUB_REF --github-url $GITHUB_SERVER_URL --github-auth ${{ github.token }}
        env:
          TEST_MODE: true

