name: PR Checks (Basic Checks and Runner)

on: push

jobs:
  npm-test:
    name: Unit Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v3
      - name: npm test
        run: |
          # Run any commands referenced in package.json using Bash, otherwise
          # we won't be able to find them on Windows.
          npm config set script-shell bash
          npm test
